version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: api-explorer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-password123}

  frontend:
    build: ./frontend
    container_name: api-explorer-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: npm run dev

  rails:
    build: ./api-explorer-rails
    container_name: api-explorer-rails
    ports:
      - "3004:3004"
    depends_on:
      - redis
    volumes:
      - ./api-explorer-rails:/app
    env_file:
      - ./api-explorer-rails/.env
    command: rails s -b 0.0.0.0 -p 3004

  django:
    build: ./api-explorer-django
    container_name: api-explorer-django
    ports:
      - "3003:3003"
    depends_on:
      - redis
    volumes:
      - ./api-explorer-django:/app
    env_file:
      - ./api-explorer-django/.env
    command: python manage.py runserver 0.0.0.0:3003

  deno:
    build: ./api-explorer-deno
    container_name: api-explorer-deno
    ports:
      - "3005:3005"
    depends_on:
      - redis
    volumes:
      - ./api-explorer-deno:/app
    env_file:
      - ./api-explorer-deno/.env
    command: deno run --allow-net --allow-read --allow-env --reload --watch main.ts

  node:
    build: ./api-explorer-node
    container_name: api-explorer-node
    ports:
      - "3001:3001"
    depends_on:
      - redis
    volumes:
      - ./api-explorer-node:/app
    env_file:
      - ./api-explorer-node/.env
    command: npm run dev

  fastapi:
    build: ./api-explorer-fastapi
    container_name: api-explorer-fastapi
    ports:
      - "3002:3002"
    depends_on:
      - redis
    volumes:
      - ./api-explorer-fastapi:/app
    env_file:
      - ./api-explorer-fastapi/.env
    command: uvicorn main:app --host 0.0.0.0 --port 3002 --reload

volumes:
  redis-data: